services:
  # Vue.js Frontend
  web:
    container_name: groceries-web
    build:
      context: .
      dockerfile: Dockerfile.web  # Use Vue-specific Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    depends_on:
      - firebase

  # Firebase Emulators
  firebase:
    container_name: firebase-emulators
    build:
      context: .
      dockerfile: Dockerfile.firebase  # Use Firebase-specific Dockerfile
    working_dir: /firebase
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        firebase emulators:start --import=./seed-data --project unpack-the-pantry-fc442
    volumes:
      - "./firebase:/firebase"
      - "./firebase/service-account-key.json:/firebase/service-account-key.json"
      - "./firebase.json:/firebase/firebase.json"
      - "./firestore-seed:/firebase/seed-data"
      - "/home/ergerodr/.config/configstore:/root/.config/configstore"
    ports:
      - "9099:9099"
      - "8080:8080"
      - "5000:5000"
      - "4000:4000"
      - "4500:4500"
    environment:
      - FIREBASE_PROJECT=demo-project
      - HOST=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=/firebase/service-account-key.json