services:
  # Vue.js Frontend
  web:
    container_name: groceries-web
    build:
      context: .
      dockerfile: Dockerfile.web  # Use Vue-specific Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - "/frugalFeast/node_modules"
      - ".:/frugalFeast"
    depends_on:
      - firebase
    networks:
      - app-network

  # Firebase Emulators
  firebase:
    container_name: firebase-emulators
    build:
      context: .
      dockerfile: Dockerfile.firebase  # Use Firebase-specific Dockerfile
    stdin_open: true
    tty: true
    working_dir: /frugalFeast
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        firebase emulators:start --project unpack-the-pantry-fc442
    volumes:
      - "./firebase.json:/frugalFeast/firebase.json"  # Main Firebase config
      - "./.firebaserc:/frugalFeast/.firebaserc"      # Firebase project settings
      - "./firestore.rules:/frugalFeast/firestore.rules"  # Firestore security rules
      - "./storage.rules:/frugalFeast/storage.rules"  # Storage security rules
      - "./firebase/service-account-key.json:/frugalFeast/service-account-key.json"  # Service account credentials
      - "./firebase/functions:/frugalFeast/firebase/functions"  # Firebase Cloud Functions directory
      - "./firestore-seed:/frugalFeast/firestore-seed"  # Firestore data imports
      - "/home/ergerodr/.config/configstore:/root/.config/configstore"  # Persist Firebase CLI login
    ports:
      - "9099:9099"
      - "9299:9299"
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "4000:4000"
      - "4500:4500"
    environment:
      - FIREBASE_PROJECT=demo-project
      - HOST=0.0.0.0
      - GOOGLE_APPLICATION_CREDENTIALS=/frugalFeast/service-account-key.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge