# Use Node.js image for Firebase Emulators
FROM node:18-bullseye

# Set working directory
WORKDIR /frugalFeast

# Install Java (Required for Firebase Emulators)
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    rm -rf /var/lib/apt/lists/*

# Install Firebase CLI globally
RUN npm install -g firebase-tools

# Verify Firebase CLI installation
RUN firebase --version

EXPOSE 4000
# Default command: Start Firebase emulators
CMD ["firebase", "emulators:start" , "--", "debug"]